"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import math
import time


class P12(object):

    @staticmethod
    def run():
        c = 0
        t = 1
        diff = 1
        while c <= 500:
            diff += 1
            t += diff
            c = P12.find_all_divisors(t)

        print(t, c)

    @staticmethod
    def find_all_divisors(n):
        c = 0
        for i in range(1, round(math.sqrt(n) + 1)):
            if n % i == 0:
                c += 2
        return c


if __name__ == '__main__':
    start_time = time.time()
    P12.run()
    print("--- %s seconds ---" % (time.time() - start_time))
