"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


class P2(object):

    @staticmethod
    def run():
        a = 1
        b = 2
        even_sum = b
        while True:
            tmp = b
            b = a + b
            a = tmp
            if b > 4e6:
                break
            if b % 2 == 0:
                even_sum += b
        print(even_sum)  # answer is 4613732


if __name__ == '__main__':
    P2.run()
